name: Depends
on:
  workflow_run:
    workflows: ["Babellint"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: OMG
        run: |
          echo "HAI"
