name: Publish

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  print-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tag is ${{ github.event.inputs.tag }} 
