name: Automatic Releases

on:
  push:
    branches:
      - main

jobs:
  newrelease:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Next semver
        id: build
        run: |
          LATEST_TAG=$(git ls-remote --tags origin |awk -F \/ '{print $NF}'|sort -Vr|head -1)
          NEXT_TAG=$(docker run --rm alpine/semver:latest semver -c -i patch ${LATEST_TAG})
          echo "::set-output name=tag::$NEXT_TAG"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.build.outputs.tag}}"
